package com.example.tcgcarddetectionapp.models

data class AddRemoveCardModel (
    val userid : String? = null,
    val cardid: String,
    val setcode: String,
    var quantity: Int,
    var rarity: String? = null,
    val game: String,
    val price: Double,
    val cardname: String,
    val attribute: String? = null,
    val level: String? = null,
    val type: String? = null,
    val description: String? = null,
    val atk: String? = null,
    val def: String? = null,
    val cost: String? = null,
    val hp: String? = null,
    val abilities: Array<Ability>? = null,
    val evolvesFrom: String? = null,
    val retreat: Array<String>? = null,
    val weaknesses: Array<Weakness>? = null,
    val attacks: Array<Attack>? = null,
    var purchaseurl: String? = null,
    val frameType: String? = null,
    val color: Array<String>? = null,
    val subcollection: String? = null,
)